# Generated by Django 5.1.5 on 2025-02-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('node_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('node_name', models.CharField(max_length=50, null=True)),
                ('total_menory', models.IntegerField(default=0, null=True)),
                ('remaining_menory', models.IntegerField(default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(default='offline', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
