# Generated by Django 5.1.5 on 2025-02-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedkey',
            name='value',
            field=models.BinaryField(max_length=50, null=True),
        ),
    ]
