version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_lan_tracer
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracer
      MYSQL_CHARSET: utf8mb4
    ports:
      - "3308:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always


  redis:
    image: redis:latest
    container_name: lan_tracer
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data
    restart: always